version: "3.8"

services:
  backend:
    build:
      context: ./event-management-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./event-management-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
