version: "3.8" # Specify the version of Docker Compose

services:
  backend:
    build:
      context: ./event-management-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./event-management-backend/uploads:/app/uploads
    env_file:
      - .env.prod # Specify the environment file

  frontend:
    build:
      context: ./event-management-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - .env.prod # Specify the environment file
