name: Deploy to Self-Hosted Server

on:
  push:
    branches:
      - main # Change to your default branch if necessary

jobs:
  build:
    runs-on: self-hosted # Specify that this job should run on a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: |
          sudo docker-compose -f docker-compose.prod.yml build

      - name: Run Docker Containers
        run: |
          # Stop and remove existing containers
          sudo docker-compose -f docker-compose.prod.yml down || true

          # Run the containers in detached mode
          sudo docker-compose -f docker-compose.prod.yml up -d
