name: Deploy to Self-Hosted Server

on:
  push:
    branches:
      - main # Change to your default branch if necessary

jobs:
  deploy:
    runs-on: self-hosted # Specify that this job should run on a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Frontend Docker Image
        run: |
          # Navigate to the frontend directory and build the Docker image
          cd event-management-frontend
          sudo docker build -t frontend-image:latest .

      - name: Build Backend Docker Image
        run: |
          # Navigate to the backend directory and build the Docker image
          cd event-management-backend
          sudo docker build -t backend-image:latest .

      - name: Stop and Remove Existing Frontend Container
        run: |
          # Stop and remove existing frontend container if it exists
          sudo docker stop frontend || true
          sudo docker rm frontend || true

      - name: Stop and Remove Existing Backend Container
        run: |
          # Stop and remove existing backend container if it exists
          sudo docker stop backend || true
          sudo docker rm backend || true

      - name: Run Frontend Container
        run: |
          # Run the frontend container in detached mode
          sudo docker run -d --name frontend -p 3000:80 frontend-image:latest

      - name: Run Backend Container with Volume
        run: |
          # Run the backend container in detached mode with a volume
          sudo docker run -d \
            --name backend \
            -p 8000:80 \
            -v backend_data:/app/uploads \ # Adjust the path according to your app
            backend-image:latest
